services:
  public_app:
    container_name: todo_trf_frontend
    build:
      context: ./todo_public_web
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    env_file:
      - ./todo_public_web/.env


  backend:
    container_name: todo_trf_backend
    restart: unless-stopped
    build:
      context: ./todo_backend
      dockerfile: Dockerfile
    env_file:
      - ./todo_backend/.env
    ports:
      - "4000:4000"

  postgres_db:
    container_name: postgres_db
    image: postgres:16
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=todo_trf_user
      - POSTGRES_PASSWORD=todo_trf_password
      - LANG=en_US.utf8
      - LC_COLLATE=C
      - LC_CTYPE=en_US.UTF-8
    

volumes:
  postgres_data:
