services:
  # nextjs-app:
  #   container_name: todo_trf_front_end
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - '3000:3000'
  #   environment:
  #     - NODE_ENV=production
  #   restart: unless-stopped


  # app:
  #   image: node:alpine
  #   volumes:
  #     - .:/app
  #   working_dir: /app
  #   command: sh -c "npm install && npm start"

  postgres_db:
    container_name: postgres_db
    image: postgres:16
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=todo_trf_user
      - POSTGRES_PASSWORD=todo_trf_password
      - LANG=en_US.utf8
      - LC_COLLATE=C
      - LC_CTYPE=en_US.UTF-8
    # networks:
    #   - todo_trf_network

   

networks:
  todo_trf_network:
    name: todo_trf_network
    driver: bridge

volumes:
  postgres_data:
